device: cuda
use_amp: false
seed: 1000
dataset_repo_id: lerobot/aloha_sim_transfer_cube_human
training:
  offline_steps: 100000
  online_steps: 0
  online_steps_between_rollouts: 1
  online_sampling_ratio: 0.5
  online_env_seed: 114514
  eval_freq: 10000
  save_freq: 25000
  log_freq: 250
  save_model: true
  batch_size: 8
  lr: 1.0e-05
  lr_backbone: 1.0e-05
  weight_decay: 0.0001
  grad_clip_norm: 10
  override_dataset_stats:
    observation.images.top:
      mean:
      - - - 0.485
      - - - 0.456
      - - - 0.406
      std:
      - - - 0.229
      - - - 0.224
      - - - 0.225
  delta_timestamps:
    action:
    - 0.0
    - 0.02
    - 0.04
    - 0.06
    - 0.08
    - 0.1
    - 0.12
    - 0.14
    - 0.16
    - 0.18
    - 0.2
    - 0.22
    - 0.24
    - 0.26
    - 0.28
    - 0.3
    - 0.32
    - 0.34
    - 0.36
    - 0.38
    - 0.4
    - 0.42
    - 0.44
    - 0.46
    - 0.48
    - 0.5
    - 0.52
    - 0.54
    - 0.56
    - 0.58
    - 0.6
    - 0.62
    - 0.64
    - 0.66
    - 0.68
    - 0.7
    - 0.72
    - 0.74
    - 0.76
    - 0.78
    - 0.8
    - 0.82
    - 0.84
    - 0.86
    - 0.88
    - 0.9
    - 0.92
    - 0.94
    - 0.96
    - 0.98
    - 1.0
    - 1.02
    - 1.04
    - 1.06
    - 1.08
    - 1.1
    - 1.12
    - 1.14
    - 1.16
    - 1.18
    - 1.2
    - 1.22
    - 1.24
    - 1.26
    - 1.28
    - 1.3
    - 1.32
    - 1.34
    - 1.36
    - 1.38
    - 1.4
    - 1.42
    - 1.44
    - 1.46
    - 1.48
    - 1.5
    - 1.52
    - 1.54
    - 1.56
    - 1.58
    - 1.6
    - 1.62
    - 1.64
    - 1.66
    - 1.68
    - 1.7
    - 1.72
    - 1.74
    - 1.76
    - 1.78
    - 1.8
    - 1.82
    - 1.84
    - 1.86
    - 1.88
    - 1.9
    - 1.92
    - 1.94
    - 1.96
    - 1.98
eval:
  n_episodes: 50
  batch_size: 50
  use_async_envs: false
wandb:
  enable: true
  disable_artifact: false
  project: lerobot
  notes: ''
fps: 50
env:
  name: aloha
  task: AlohaTransferCube-v0
  state_dim: 14
  action_dim: 14
  fps: ${fps}
  episode_length: 400
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
policy:
  name: act
  n_obs_steps: 1
  chunk_size: 100
  n_action_steps: 100
  input_shapes:
    observation.images.top:
    - 3
    - 480
    - 640
    observation.state:
    - ${env.state_dim}
  output_shapes:
    action:
    - ${env.action_dim}
  input_normalization_modes:
    observation.images.top: mean_std
    observation.state: mean_std
  output_normalization_modes:
    action: mean_std
  vision_backbone: resnet18
  pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
  replace_final_stride_with_dilation: false
  pre_norm: false
  dim_model: 512
  n_heads: 8
  dim_feedforward: 3200
  feedforward_activation: relu
  n_encoder_layers: 4
  n_decoder_layers: 1
  use_vae: true
  latent_dim: 32
  n_vae_encoder_layers: 4
  temporal_ensemble_coeff: null
  dropout: 0.1
  kl_weight: 10.0
